// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$222 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$222() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDgetattdatainfo",
        constants$89.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDgetoldattdatainfo",
        constants$188.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDgetanndatainfo",
        constants$182.const$1
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("var_index"),
        JAVA_INT.withName("var_type")
    ).withName("hdf_varlist");
    static final VarHandle const$4 = constants$222.const$3.varHandle(MemoryLayout.PathElement.groupElement("var_index"));
    static final VarHandle const$5 = constants$222.const$3.varHandle(MemoryLayout.PathElement.groupElement("var_type"));
}


