// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "index",
        constants$73.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rindex",
        constants$73.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ffs",
        constants$1.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ffsl",
        constants$78.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ffsll",
        constants$78.const$3
    );
}


