// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$204 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$204() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Vsetclass",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Visvg",
        constants$93.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Visvs",
        constants$93.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Vgetid",
        constants$93.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Vgetnext",
        constants$93.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Vgetname",
        constants$5.const$3
    );
}


