// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "strtol",
        constants$9.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strtoul",
        constants$9.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "strtoq",
        constants$9.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "strtouq",
        constants$9.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strtoll",
        constants$9.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "strtoull",
        constants$9.const$2
    );
}


