// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$208 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$208() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vsdestroynode",
        constants$24.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vfdestroynode",
        constants$24.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "VSattach",
        constants$132.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "VSdetach",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "VSQuerytag",
        constants$1.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "VSQueryref",
        constants$1.const$5
    );
}


