// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "erand48",
        constants$38.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "lrand48",
        constants$38.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nrand48",
        constants$33.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mrand48",
        constants$38.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "jrand48",
        constants$33.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "srand48",
        constants$55.const$5
    );
}


