// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vsscanf",
        constants$25.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fgetc",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getc",
        constants$17.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$28.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$17.const$4
    );
}


