// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Hseek",
        constants$98.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Htell",
        constants$1.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Hread",
        constants$132.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Hwrite",
        constants$132.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Htrunc",
        constants$93.const$3
    );
}


