// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "tmpnam_r",
        constants$20.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "tempnam",
        constants$21.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fflush",
        constants$17.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fflush_unlocked",
        constants$17.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fopen",
        constants$21.const$1
    );
}


