// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gethostid",
        constants$38.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sync",
        constants$61.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getpagesize",
        constants$28.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getdtablesize",
        constants$28.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "truncate",
        constants$68.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ftruncate",
        constants$114.const$5
    );
}


