// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final VarHandle const$0 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("rand_deg"));
    static final VarHandle const$1 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("rand_sep"));
    static final VarHandle const$2 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("end_ptr"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "random_r",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "srandom_r",
        constants$5.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "initstate_r",
        constants$53.const$5
    );
}


