// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct hdf_ntinfo_t {
 *     char type_name[9];
 *     char byte_order[13];
 * };
 * }
 */
public class hdf_ntinfo_t {

    public static MemoryLayout $LAYOUT() {
        return constants$122.const$0;
    }
    public static MemorySegment type_name$slice(MemorySegment seg) {
        return seg.asSlice(0, 9);
    }
    public static MemorySegment byte_order$slice(MemorySegment seg) {
        return seg.asSlice(9, 13);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


