// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct hdf_varlist {
 *     int32 var_index;
 *     hdf_vartype_t var_type;
 * };
 * }
 */
public class hdf_varlist {

    public static MemoryLayout $LAYOUT() {
        return constants$222.const$3;
    }
    public static VarHandle var_index$VH() {
        return constants$222.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32 var_index;
     * }
     */
    public static int var_index$get(MemorySegment seg) {
        return (int)constants$222.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32 var_index;
     * }
     */
    public static void var_index$set(MemorySegment seg, int x) {
        constants$222.const$4.set(seg, x);
    }
    public static int var_index$get(MemorySegment seg, long index) {
        return (int)constants$222.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void var_index$set(MemorySegment seg, long index, int x) {
        constants$222.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle var_type$VH() {
        return constants$222.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * hdf_vartype_t var_type;
     * }
     */
    public static int var_type$get(MemorySegment seg) {
        return (int)constants$222.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * hdf_vartype_t var_type;
     * }
     */
    public static void var_type$set(MemorySegment seg, int x) {
        constants$222.const$5.set(seg, x);
    }
    public static int var_type$get(MemorySegment seg, long index) {
        return (int)constants$222.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void var_type$set(MemorySegment seg, long index, int x) {
        constants$222.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


