// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$105 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$105() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getgid",
        constants$28.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getegid",
        constants$28.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getgroups",
        constants$5.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setuid",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setreuid",
        constants$93.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "seteuid",
        constants$1.const$5
    );
}


