// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fileno_unlocked",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pclose",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "popen",
        constants$21.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ctermid",
        constants$20.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "flockfile",
        constants$24.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ftrylockfile",
        constants$17.const$4
    );
}


