// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DFR8Pshutdown",
        constants$28.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DFGRgetlutdims",
        constants$146.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DFGRreqlutil",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DFGRgetlut",
        constants$151.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DFGRgetimdims",
        constants$146.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DFGRreqimil",
        constants$1.const$5
    );
}


