// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$226 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$226() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDreadattr",
        constants$132.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDwritedata",
        constants$42.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDsetdatastrs",
        constants$42.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDsetcal",
        constants$226.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDsetfillvalue",
        constants$5.const$3
    );
}


