// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$113() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "endusershell",
        constants$61.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setusershell",
        constants$61.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "daemon",
        constants$93.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "chroot",
        constants$17.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getpass",
        constants$20.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fsync",
        constants$1.const$5
    );
}


