// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__toupper_l",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "toupper_l",
        constants$5.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("quot"),
        JAVA_LONG.withName("rem")
    ).withName("");
    static final VarHandle const$3 = constants$8.const$2.varHandle(MemoryLayout.PathElement.groupElement("quot"));
    static final VarHandle const$4 = constants$8.const$2.varHandle(MemoryLayout.PathElement.groupElement("rem"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "imaxabs",
        constants$8.const$5
    );
}


