// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "isalpha",
        constants$1.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "iscntrl",
        constants$1.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "isdigit",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "islower",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "isgraph",
        constants$1.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "isprint",
        constants$1.const$5
    );
}


