// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "unsetenv",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "clearenv",
        constants$28.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "mktemp",
        constants$20.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mkstemp",
        constants$17.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mkstemps",
        constants$37.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mkdtemp",
        constants$20.const$4
    );
}


