// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$203 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$203() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Vgettagref",
        constants$89.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "VQueryref",
        constants$1.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "VQuerytag",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Vaddtagref",
        constants$98.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Ventries",
        constants$93.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Vsetname",
        constants$5.const$3
    );
}


