// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$171 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$171() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DFSDgetdatalen",
        constants$135.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DFSDgetdimlen",
        constants$138.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DFSDgetdimscale",
        constants$132.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DFSDgetrange",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DFSDgetdata",
        constants$89.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DFSDsetlengths",
        constants$159.const$2
    );
}


