// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$159 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$159() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DFGRgetimage",
        constants$151.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DFGRsetcompress",
        constants$5.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DFGRsetlutdims",
        constants$159.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DFGRsetlut",
        constants$98.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DFGRaddlut",
        constants$151.const$1
    );
}


