// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$157 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$157() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "DFR8nimages",
        constants$17.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "DFR8readref",
        constants$154.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "DFR8writeref",
        constants$154.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "DFR8restart",
        constants$28.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "DFR8lastref",
        constants$155.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "DFR8getpalref",
        constants$17.const$4
    );
}


