// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$232 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$232() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDcheckempty",
        constants$5.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDidtype",
        constants$1.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDreset_maxopenfiles",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDget_maxopenfiles",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDget_numopenfiles",
        constants$28.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDgetdatasize",
        constants$26.const$5
    );
}


