// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "pwrite",
        constants$96.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pipe",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "alarm",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sleep",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ualarm",
        constants$93.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "usleep",
        constants$1.const$5
    );
}


