// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$137 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$137() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "HDgettagsname",
        constants$136.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "HDgettagnum",
        constants$17.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "HDgetNTdesc",
        constants$76.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "HDfidtoname",
        constants$76.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Hgetntinfo",
        constants$5.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "Hishdf",
        constants$17.const$4
    );
}


