// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$214 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$214() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "VSgetdatainfo",
        constants$182.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "VSgetattdatainfo",
        constants$182.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Vgetattdatainfo",
        constants$89.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GRgetdatainfo",
        constants$182.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GRgetattdatainfo",
        constants$89.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GRgetpalinfo",
        constants$132.const$2
    );
}


