// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$149 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$149() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "Hbitwrite",
        constants$98.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "Hbitread",
        constants$132.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "Hbitseek",
        constants$98.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "Hgetbit",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "Hendbitaccess",
        constants$93.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "HPbitshutdown",
        constants$28.const$3
    );
}


