// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "dup",
        constants$1.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "dup2",
        constants$93.const$3
    );
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("__environ", RuntimeHelper.POINTER);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "execve",
        constants$25.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fexecve",
        constants$26.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "execv",
        constants$19.const$5
    );
}


