// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_put_vars_uint",
        constants$12.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_get_vars_uint",
        constants$12.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_put_vars_longlong",
        constants$12.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_get_vars_longlong",
        constants$12.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_put_vars_ulonglong",
        constants$12.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_get_vars_ulonglong",
        constants$12.const$2
    );
}


