// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_open",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_inq_path",
        constants$1.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_inq_ncid",
        constants$1.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_inq_grps",
        constants$1.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_inq_grpname",
        constants$3.const$4
    );
}


