// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_del_att",
        constants$7.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_put_att_text",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_get_att_text",
        constants$7.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_put_att_string",
        constants$10.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_get_att_string",
        constants$7.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_put_att_uchar",
        constants$11.const$3
    );
}


