// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_rename_var",
        constants$7.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_copy_var",
        constants$16.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_put_var1_text",
        constants$7.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_get_var1_text",
        constants$7.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_put_var1_uchar",
        constants$7.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_get_var1_uchar",
        constants$7.const$0
    );
}


