// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_put_var1_float",
        constants$7.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_get_var1_float",
        constants$7.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_put_var1_double",
        constants$7.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_get_var1_double",
        constants$7.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_put_var1_ushort",
        constants$7.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_get_var1_ushort",
        constants$7.const$0
    );
}


