// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc__enddef",
        constants$20.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_enddef",
        constants$19.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_sync",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_abort",
        constants$19.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nc_close",
        constants$19.const$5
    );
}


