// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_set_base_pe",
        constants$1.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_inq_base_pe",
        constants$3.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nctypelen",
        constants$19.const$5
    );
    static final VarHandle const$3 = JAVA_INT.varHandle();
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("ncerr", JAVA_INT);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("ncopts", JAVA_INT);
}


