// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nc_inq_compound_fieldindex",
        constants$7.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nc_inq_compound_fieldoffset",
        constants$8.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nc_inq_compound_fieldtype",
        constants$8.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nc_inq_compound_fieldndims",
        constants$8.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nc_inq_compound_fielddim_sizes",
        constants$8.const$4
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("len"),
        RuntimeHelper.POINTER.withName("p")
    ).withName("");
}


