// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ncdimid",
        constants$3.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ncdiminq",
        constants$7.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ncdimrename",
        constants$7.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ncattput",
        constants$61.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ncattinq",
        constants$7.const$3
    );
}


