// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$267 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$267() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5VL_dataset_class_t.specific.class, "apply", constants$262.const$3);
    static final VarHandle const$1 = constants$264.const$3.varHandle(MemoryLayout.PathElement.groupElement("specific"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_dataset_class_t.optional.class, "apply", constants$262.const$3);
    static final VarHandle const$3 = constants$264.const$3.varHandle(MemoryLayout.PathElement.groupElement("optional"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5VL_dataset_class_t.close.class, "apply", constants$17.const$2);
    static final VarHandle const$5 = constants$264.const$3.varHandle(MemoryLayout.PathElement.groupElement("close"));
}


