// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$214 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$214() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$121.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5Z_filter_func_t.class, "apply", constants$214.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$214.const$1
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("func"),
        RuntimeHelper.POINTER.withName("op_data")
    ).withName("H5Z_cb_t");
    static final VarHandle const$5 = constants$214.const$4.varHandle(MemoryLayout.PathElement.groupElement("func"));
}


