// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$206 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$206() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5FDunlock",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5FDdriver_query",
        constants$18.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("storage_type"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("nlinks"),
        JAVA_LONG.withName("max_corder"),
        JAVA_BOOLEAN.withName("mounted"),
        MemoryLayout.paddingLayout(7)
    ).withName("H5G_info_t");
    static final VarHandle const$3 = constants$206.const$2.varHandle(MemoryLayout.PathElement.groupElement("storage_type"));
    static final VarHandle const$4 = constants$206.const$2.varHandle(MemoryLayout.PathElement.groupElement("nlinks"));
    static final VarHandle const$5 = constants$206.const$2.varHandle(MemoryLayout.PathElement.groupElement("max_corder"));
}


