// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$106 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$106() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Dvlen_get_buf_size",
        constants$54.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Dfill",
        constants$57.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Dset_extent",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Dflush",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Drefresh",
        constants$19.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Dscatter",
        constants$106.const$5
    );
}


