// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$238 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$238() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("file")
    ).withName("");
    static final VarHandle const$1 = constants$238.const$0.varHandle(MemoryLayout.PathElement.groupElement("file"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("filename"),
        JAVA_LONG.withName("fapl_id"),
        RuntimeHelper.POINTER.withName("accessible")
    ).withName("");
    static final VarHandle const$3 = constants$238.const$2.varHandle(MemoryLayout.PathElement.groupElement("filename"));
    static final VarHandle const$4 = constants$238.const$2.varHandle(MemoryLayout.PathElement.groupElement("fapl_id"));
    static final VarHandle const$5 = constants$238.const$2.varHandle(MemoryLayout.PathElement.groupElement("accessible"));
}


