// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$236 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$236() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_istore_k",
        constants$44.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_index",
        constants$162.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_nindexes",
        constants$44.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_phase_change",
        constants$41.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_sizes",
        constants$41.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_sym_k",
        constants$41.const$4
    );
}


