// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$229 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$229() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("dset_id")
    ).withName("");
    static final VarHandle const$1 = constants$229.const$0.varHandle(MemoryLayout.PathElement.groupElement("dset_id"));
    static final VarHandle const$2 = constants$229.const$0.varHandle(MemoryLayout.PathElement.groupElement("dset_id"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("op_type"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("size")
            ).withName("get_binary_size"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buf"),
                JAVA_LONG.withName("buf_size")
            ).withName("get_binary"),
            MemoryLayout.structLayout(
                JAVA_LONG.withName("tcpl_id")
            ).withName("get_tcpl")
        ).withName("args")
    ).withName("H5VL_datatype_get_args_t");
    static final VarHandle const$4 = constants$229.const$3.varHandle(MemoryLayout.PathElement.groupElement("op_type"));
    static final UnionLayout const$5 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("size")
        ).withName("get_binary_size"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("buf"),
            JAVA_LONG.withName("buf_size")
        ).withName("get_binary"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tcpl_id")
        ).withName("get_tcpl")
    ).withName("");
}


