// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$249 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$249() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pfill_value_defined",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_alloc_time",
        constants$18.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_chunk",
        constants$21.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_chunk_opts",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_dset_no_attrs_hint",
        constants$18.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Pget_external",
        constants$249.const$5
    );
}


