// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$356 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$356() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_elink_cb",
        constants$36.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_elink_fapl",
        constants$58.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_elink_prefix",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_nlinks",
        constants$58.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Padd_merge_committed_dtype_path",
        constants$17.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pfree_merge_committed_dtype_paths",
        constants$19.const$1
    );
}


