// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$215 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$215() {}
    static final VarHandle const$0 = constants$214.const$4.varHandle(MemoryLayout.PathElement.groupElement("op_data"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5Z_can_apply_func_t.class, "apply", constants$215.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$215.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5Z_set_local_func_t.class, "apply", constants$215.const$1);
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


