// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$258 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$258() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_data_transform",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_edc_check",
        constants$46.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_filter_callback",
        constants$42.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_hyper_vector_size",
        constants$41.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pset_preserve",
        constants$182.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_type_conv_cb",
        constants$42.const$5
    );
}


