// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tset_fields",
        constants$52.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tset_ebias",
        constants$41.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tset_norm",
        constants$46.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tset_inpad",
        constants$46.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Tset_cset",
        constants$46.const$4
    );
}


