// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$335 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$335() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_page_buffer_size",
        constants$27.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_sieve_buf_size",
        constants$17.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_small_data_block_size",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_vol_id",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_vol_info",
        constants$17.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_alignment",
        constants$330.const$5
    );
}


