// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$118 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$118() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getchar_unlocked",
        constants$13.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fgetc_unlocked",
        constants$15.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fputc",
        constants$22.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "putc",
        constants$22.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "putchar",
        constants$21.const$0
    );
}


