// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$348 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$348() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_efile_prefix",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_prefix",
        constants$17.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_printf_gap",
        constants$58.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_view",
        constants$64.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_btree_ratios",
        constants$27.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Pget_buffer",
        constants$348.const$5
    );
}


