// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$218 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$218() {}
    static final VarHandle const$0 = constants$217.const$0.varHandle(MemoryLayout.PathElement.groupElement("can_apply"));
    static final VarHandle const$1 = constants$217.const$0.varHandle(MemoryLayout.PathElement.groupElement("set_local"));
    static final VarHandle const$2 = constants$217.const$0.varHandle(MemoryLayout.PathElement.groupElement("filter"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Zregister",
        constants$15.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Zunregister",
        constants$21.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Zfilter_avail",
        constants$21.const$0
    );
}


