// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$305 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$305() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5VL_group_class_t.optional.class, "apply", constants$292.const$4);
    static final VarHandle const$1 = constants$303.const$1.varHandle(MemoryLayout.PathElement.groupElement("optional"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_group_class_t.close.class, "apply", constants$18.const$0);
    static final VarHandle const$3 = constants$303.const$1.varHandle(MemoryLayout.PathElement.groupElement("close"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("create"),
        RuntimeHelper.POINTER.withName("copy"),
        RuntimeHelper.POINTER.withName("move"),
        RuntimeHelper.POINTER.withName("get"),
        RuntimeHelper.POINTER.withName("specific"),
        RuntimeHelper.POINTER.withName("optional")
    ).withName("H5VL_link_class_t");
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


