// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$259 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$259() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_link_phase_change",
        constants$50.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_local_heap_size_hint",
        constants$40.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_char_encoding",
        constants$44.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_char_encoding",
        constants$45.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_elink_acc_flags",
        constants$44.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_elink_cb",
        constants$41.const$4
    );
}


