// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$192 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$192() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Lmove",
        constants$32.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Lcopy",
        constants$32.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Lcreate_hard",
        constants$32.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Lcreate_hard_async",
        constants$32.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Lcreate_soft",
        constants$97.const$1
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Lcreate_soft_async",
        constants$192.const$5
    );
}


