// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5_atclose_func_t.class, "apply", constants$12.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$12.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5open",
        constants$13.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5atclose",
        constants$13.const$4
    );
}


