// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$181 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$181() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Freset_mdc_hit_rate_stats",
        constants$19.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Fget_name",
        constants$19.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Fget_info2",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Fget_metadata_read_retry_info",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Fstart_swmr_write",
        constants$19.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Fget_free_sections",
        constants$178.const$5
    );
}


