// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$194 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$194() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5FD_class_t.read.class, "apply", constants$194.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$194.const$0
    );
    static final VarHandle const$3 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("read"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5FD_class_t.write.class, "apply", constants$194.const$0);
    static final VarHandle const$5 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("write"));
}


