// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$88 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$88() {}
    static final VarHandle const$0 = constants$87.const$2.varHandle(MemoryLayout.PathElement.groupElement("data_size"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5A_operator2_t.class, "apply", constants$61.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Aclose",
        constants$19.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Acreate2",
        constants$88.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Acreate_by_name",
        constants$88.const$5
    );
}


