// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$286 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$286() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5VL_blob_class_t.specific.class, "apply", constants$15.const$0);
    static final VarHandle const$1 = constants$284.const$5.varHandle(MemoryLayout.PathElement.groupElement("specific"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_blob_class_t.optional.class, "apply", constants$15.const$0);
    static final VarHandle const$3 = constants$284.const$5.varHandle(MemoryLayout.PathElement.groupElement("optional"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("cmp"),
        RuntimeHelper.POINTER.withName("to_str"),
        RuntimeHelper.POINTER.withName("from_str")
    ).withName("H5VL_token_class_t");
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5VL_token_class_t.cmp.class, "apply", constants$14.const$5);
}


