// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tget_fields",
        constants$48.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tget_ebias",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tget_norm",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tget_inpad",
        constants$19.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Tget_strpad",
        constants$19.const$5
    );
}


