// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5E_MOUNT_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5E_NOTHDF5_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5E_TRUNCATED_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5E_UNMOUNT_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5E_CANTMERGE_g", JAVA_LONG);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5E_CANTREVIVE_g", JAVA_LONG);
}


