// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$311 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$311() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Zget_filter_info",
        constants$22.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5P_cls_create_func_t.class, "apply", constants$17.const$5);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5P_cls_copy_func_t.class, "apply", constants$79.const$5);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$79.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5P_cls_close_func_t.class, "apply", constants$17.const$5);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5P_prp_cb1_t.class, "apply", constants$17.const$2);
}


