// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Tset_ebias",
        constants$58.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tset_norm",
        constants$64.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tset_inpad",
        constants$64.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tset_cset",
        constants$64.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tset_strpad",
        constants$64.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Tconvert",
        constants$70.const$5
    );
}


