// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$283 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$283() {}
    static final VarHandle const$0 = constants$282.const$5.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$1 = constants$282.const$5.varHandle(MemoryLayout.PathElement.groupElement("lapl_id"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("name"),
        JAVA_INT.withName("idx_type"),
        JAVA_INT.withName("order"),
        JAVA_LONG.withName("n"),
        JAVA_LONG.withName("lapl_id")
    ).withName("H5VL_loc_by_idx");
    static final VarHandle const$3 = constants$283.const$2.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$4 = constants$283.const$2.varHandle(MemoryLayout.PathElement.groupElement("idx_type"));
    static final VarHandle const$5 = constants$283.const$2.varHandle(MemoryLayout.PathElement.groupElement("order"));
}


