// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final VarHandle const$0 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("peak_alloc_blocks_count"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5open",
        constants$14.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5close",
        constants$14.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5dont_atexit",
        constants$14.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5garbage_collect",
        constants$14.const$1
    );
}


