// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "putc",
        constants$23.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "putchar",
        constants$21.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fputc_unlocked",
        constants$23.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "putc_unlocked",
        constants$23.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "putchar_unlocked",
        constants$21.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getw",
        constants$15.const$4
    );
}


