// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final VarHandle const$0 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$1 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("rc"));
    static final VarHandle const$2 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("atime"));
    static final VarHandle const$3 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("mtime"));
    static final VarHandle const$4 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("ctime"));
    static final VarHandle const$5 = constants$70.const$3.varHandle(MemoryLayout.PathElement.groupElement("btime"));
}


