// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Tpack",
        constants$19.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tenum_create",
        constants$0.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tenum_insert",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tenum_nameof",
        constants$33.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tenum_valueof",
        constants$36.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Tvlen_create",
        constants$0.const$4
    );
}


