// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$139 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$139() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5E_CANTMARKCLEAN_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5E_CANTMARKDIRTY_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5E_CANTMARKSERIALIZED_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5E_CANTMARKUNSERIALIZED_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5E_CANTNOTIFY_g", JAVA_LONG);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5E_CANTPIN_g", JAVA_LONG);
}


