// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$272 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$272() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Rget_region",
        constants$45.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Rget_name",
        constants$272.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Sclose",
        constants$19.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Scombine_hyperslab",
        constants$272.const$4
    );
}


