// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$199 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$199() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5FDread",
        constants$187.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5FDwrite",
        constants$187.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5FDflush",
        constants$188.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5FDtruncate",
        constants$188.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5FDlock",
        constants$189.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5FDunlock",
        constants$15.const$2
    );
}


