// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$157 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$157() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5E_NOSPACE_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5E_OBJOPEN_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5E_SYSERRSTR_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5E_BADSIZE_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5E_CANTCONVERT_g", JAVA_LONG);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5E_walk2_t.class, "apply", constants$22.const$0);
}


