// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$426 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$426() {}
    static final VarHandle const$0 = constants$425.const$5.varHandle(MemoryLayout.PathElement.groupElement("fapl_id"));
    static final VarHandle const$1 = constants$425.const$5.varHandle(MemoryLayout.PathElement.groupElement("file_handle"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("is_enabled"),
        RuntimeHelper.POINTER.withName("is_currently_logging")
    ).withName("H5VL_native_file_get_mdc_logging_status_t");
    static final VarHandle const$3 = constants$426.const$2.varHandle(MemoryLayout.PathElement.groupElement("is_enabled"));
    static final VarHandle const$4 = constants$426.const$2.varHandle(MemoryLayout.PathElement.groupElement("is_currently_logging"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("accesses"),
        RuntimeHelper.POINTER.withName("hits"),
        RuntimeHelper.POINTER.withName("misses"),
        RuntimeHelper.POINTER.withName("evictions"),
        RuntimeHelper.POINTER.withName("bypasses")
    ).withName("H5VL_native_file_get_page_buffering_stats_t");
}


