// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$333 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$333() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5VLlink_move",
        constants$332.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5VLlink_get",
        constants$326.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5VLlink_specific",
        constants$326.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5VLlink_optional",
        constants$326.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLobject_open",
        constants$333.const$4
    );
}


