// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$178 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$178() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Fget_vfd_handle",
        constants$92.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Fmount",
        constants$43.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Funmount",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Fget_freespace",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Fget_filesize",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Fget_eoa",
        constants$18.const$3
    );
}


