// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$393 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$393() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5T_conv_t.class, "apply", constants$392.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$392.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tregister",
        constants$393.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tunregister",
        constants$393.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "H5Tfind",
        constants$393.const$5
    );
}


