// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$245 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$245() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_gc_references",
        constants$45.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_libver_bounds",
        constants$50.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_mdc_config",
        constants$44.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pset_mdc_log_options",
        constants$245.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_meta_block_size",
        constants$40.const$0
    );
}


