// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$186 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$186() {}
    static final VarHandle const$0 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("sb_encode"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5FD_class_t.sb_decode.class, "apply", constants$16.const$0);
    static final VarHandle const$2 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("sb_decode"));
    static final VarHandle const$3 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("fapl_size"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5FD_class_t.fapl_get.class, "apply", constants$118.const$5);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$118.const$5
    );
}


