// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$240 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$240() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_cache",
        constants$103.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_core_write_tracking",
        constants$42.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_driver",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_driver_info",
        constants$46.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_elink_file_cache_size",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_evict_on_close",
        constants$18.const$3
    );
}


