// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$382 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$382() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5FDget_eof",
        constants$369.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5FDget_vfd_handle",
        constants$17.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5FDread",
        constants$371.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5FDwrite",
        constants$371.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5FDread_vector",
        constants$372.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5FDwrite_vector",
        constants$372.const$0
    );
}


