// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5check_version",
        constants$16.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5is_library_threadsafe",
        constants$15.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5free_memory",
        constants$15.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5allocate_memory",
        constants$16.const$4
    );
}


