// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Adelete",
        constants$44.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Adelete_by_idx",
        constants$63.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Adelete_by_name",
        constants$43.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Aexists",
        constants$44.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Aexists_by_name",
        constants$43.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Aget_create_plist",
        constants$10.const$2
    );
}


