// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$189 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$189() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("dstbuf"),
        JAVA_LONG.withName("dst_off"),
        RuntimeHelper.POINTER.withName("srcbuf"),
        JAVA_LONG.withName("src_off"),
        JAVA_LONG.withName("len")
    ).withName("H5FD_ctl_memcpy_args_t");
    static final VarHandle const$1 = constants$189.const$0.varHandle(MemoryLayout.PathElement.groupElement("dstbuf"));
    static final VarHandle const$2 = constants$189.const$0.varHandle(MemoryLayout.PathElement.groupElement("dst_off"));
    static final VarHandle const$3 = constants$189.const$0.varHandle(MemoryLayout.PathElement.groupElement("srcbuf"));
    static final VarHandle const$4 = constants$189.const$0.varHandle(MemoryLayout.PathElement.groupElement("src_off"));
    static final VarHandle const$5 = constants$189.const$0.varHandle(MemoryLayout.PathElement.groupElement("len"));
}


