// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$242 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$242() {}
    static final VarHandle const$0 = constants$241.const$5.varHandle(MemoryLayout.PathElement.groupElement("op_type"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("name"),
            RuntimeHelper.POINTER.withName("child_file"),
            JAVA_LONG.withName("fmpl_id")
        ).withName("mount"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("name")
        ).withName("unmount"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("grp_id")
        ).withName("flush"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("grp_id")
        ).withName("refresh")
    ).withName("");
    static final VarHandle const$2 = constants$224.const$4.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("grp_id")
    ).withName("");
    static final VarHandle const$4 = constants$242.const$3.varHandle(MemoryLayout.PathElement.groupElement("grp_id"));
    static final VarHandle const$5 = constants$242.const$3.varHandle(MemoryLayout.PathElement.groupElement("grp_id"));
}


