// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$135 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$135() {}
    static final VarHandle const$0 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("cls_id"));
    static final VarHandle const$1 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("maj_num"));
    static final VarHandle const$2 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("min_num"));
    static final VarHandle const$3 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("line"));
    static final VarHandle const$4 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("func_name"));
    static final VarHandle const$5 = constants$134.const$5.varHandle(MemoryLayout.PathElement.groupElement("file_name"));
}


