// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$353 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$353() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_create_intermediate_group",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_create_intermediate_group",
        constants$64.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_est_link_info",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_link_creation_order",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_link_phase_change",
        constants$36.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_local_heap_size_hint",
        constants$17.const$5
    );
}


