// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$173 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$173() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Fincrement_filesize",
        constants$40.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Fget_file_image",
        constants$19.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_config",
        constants$44.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Fset_mdc_config",
        constants$44.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_hit_rate",
        constants$44.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_size",
        constants$97.const$2
    );
}


