// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$168() {}
    static final VarHandle const$0 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("app_file_name"));
    static final VarHandle const$1 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("app_func_name"));
    static final VarHandle const$2 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("app_line_num"));
    static final VarHandle const$3 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("op_ins_count"));
    static final VarHandle const$4 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("op_ins_ts"));
    static final VarHandle const$5 = constants$167.const$3.varHandle(MemoryLayout.PathElement.groupElement("op_exec_ts"));
}


