// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$303 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$303() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Scopy",
        constants$0.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Screate",
        constants$209.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Screate_simple",
        constants$303.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Sdecode",
        constants$61.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Sencode2",
        constants$33.const$0
    );
}


