// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Tget_size",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tget_order",
        constants$19.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tget_precision",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Tget_offset",
        constants$19.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tget_pad",
        constants$41.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Tget_sign",
        constants$19.const$0
    );
}


