// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("__clang_max_align_nonce1"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_LONG.withName("index_size"),
        JAVA_LONG.withName("heap_size")
    ).withName("H5_ih_info_t");
    static final VarHandle const$2 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("index_size"));
    static final VarHandle const$3 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("heap_size"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("total_alloc_bytes"),
        JAVA_LONG.withName("curr_alloc_bytes"),
        JAVA_LONG.withName("peak_alloc_bytes"),
        JAVA_LONG.withName("max_block_size"),
        JAVA_LONG.withName("total_alloc_blocks_count"),
        JAVA_LONG.withName("curr_alloc_blocks_count"),
        JAVA_LONG.withName("peak_alloc_blocks_count")
    ).withName("H5_alloc_stats_t");
    static final VarHandle const$5 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("total_alloc_bytes"));
}


