// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$245 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$245() {}
    static final VarHandle const$0 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("op_type"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("linfo")
        ).withName("get_info"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("name_size"),
            RuntimeHelper.POINTER.withName("name"),
            RuntimeHelper.POINTER.withName("name_len")
        ).withName("get_name"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("buf_size"),
            RuntimeHelper.POINTER.withName("buf")
        ).withName("get_val")
    ).withName("");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("linfo")
    ).withName("");
    static final VarHandle const$3 = constants$245.const$2.varHandle(MemoryLayout.PathElement.groupElement("linfo"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("name_size"),
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("name_len")
    ).withName("");
    static final VarHandle const$5 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("name_size"));
}


