// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$280 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$280() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Sselect_valid",
        constants$19.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Sset_extent_none",
        constants$19.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Sset_extent_simple",
        constants$168.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Sencode1",
        constants$42.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLregister_connector_by_name",
        constants$280.const$4
    );
}


