// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5T_STD_U32LE_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5T_STD_U64BE_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5T_STD_U64LE_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5T_STD_B8BE_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5T_STD_B8LE_g", JAVA_LONG);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5T_STD_B16BE_g", JAVA_LONG);
}


