// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Aget_info",
        constants$44.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Aget_info_by_idx",
        constants$65.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Aget_info_by_name",
        constants$83.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Aget_name",
        constants$83.const$4
    );
}


