// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$265 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$265() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_version",
        constants$103.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_file_space",
        constants$265.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_file_space",
        constants$42.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5PLset_loading_state",
        constants$21.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5PLget_loading_state",
        constants$15.const$4
    );
}


