// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$414 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$414() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5VLblob_specific",
        constants$115.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5VLblob_optional",
        constants$115.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5VLtoken_cmp",
        constants$197.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VLtoken_to_str",
        constants$414.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLtoken_from_str",
        constants$414.const$3
    );
}


