// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$49 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$49() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Tget_nmembers",
        constants$19.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Tget_member_name",
        constants$19.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Tget_member_index",
        constants$18.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Tget_member_offset",
        constants$49.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Tget_member_class",
        constants$46.const$4
    );
}


