// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$190 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$190() {}
    static final VarHandle const$0 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("cmp"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5FD_class_t.query.class, "apply", constants$117.const$4);
    static final VarHandle const$2 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("query"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(H5FD_class_t.get_type_map.class, "apply", constants$117.const$4);
    static final VarHandle const$4 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_type_map"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5FD_class_t.alloc.class, "apply", constants$175.const$5);
}


