// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$205 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$205() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5FDget_vfd_handle",
        constants$18.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5FDread",
        constants$194.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5FDwrite",
        constants$194.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5FDflush",
        constants$195.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5FDtruncate",
        constants$195.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5FDlock",
        constants$196.const$0
    );
}


