// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$208 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$208() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Gget_info",
        constants$18.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Gget_info_by_name",
        constants$44.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Gget_info_by_idx",
        constants$64.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Gflush",
        constants$19.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Grefresh",
        constants$19.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Gclose",
        constants$19.const$5
    );
}


