// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$85 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$85() {}
    static final VarHandle const$0 = constants$83.const$3.varHandle(MemoryLayout.PathElement.groupElement("num_attrs"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5O_iterate1_t.class, "apply", constants$61.const$0);
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Oopen_by_addr",
        constants$85.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Oget_info1",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Oget_info_by_name1",
        constants$44.const$3
    );
}


