// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$138 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$138() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5E_CANTDEPEND_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5E_CANTDIRTY_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5E_CANTEXPUNGE_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5E_CANTFLUSH_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5E_CANTINS_g", JAVA_LONG);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5E_CANTLOAD_g", JAVA_LONG);
}


