// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$246 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$246() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_metadata_read_attempts",
        constants$45.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_multi_type",
        constants$45.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_object_flush_cb",
        constants$41.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_sieve_buf_size",
        constants$40.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pset_small_data_block_size",
        constants$40.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_mdc_image_config",
        constants$44.const$4
    );
}


