// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$364 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$364() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5FD_class_t.fapl_get.class, "apply", constants$110.const$3);
    static final VarHandle const$1 = constants$361.const$2.varHandle(MemoryLayout.PathElement.groupElement("fapl_get"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5FD_class_t.fapl_copy.class, "apply", constants$110.const$3);
    static final VarHandle const$3 = constants$361.const$2.varHandle(MemoryLayout.PathElement.groupElement("fapl_copy"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5FD_class_t.fapl_free.class, "apply", constants$15.const$4);
    static final VarHandle const$5 = constants$361.const$2.varHandle(MemoryLayout.PathElement.groupElement("fapl_free"));
}


