// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$328 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$328() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_obj_track_times",
        constants$183.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_file_space_page_size",
        constants$17.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_file_space_strategy",
        constants$27.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_istore_k",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_index",
        constants$161.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_nindexes",
        constants$17.const$5
    );
}


