// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$289 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$289() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5VL_wrap_class_t.wrap_object.class, "apply", constants$128.const$1);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$128.const$1
    );
    static final VarHandle const$2 = constants$288.const$1.varHandle(MemoryLayout.PathElement.groupElement("wrap_object"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(H5VL_wrap_class_t.unwrap_object.class, "apply", constants$118.const$5);
    static final VarHandle const$4 = constants$288.const$1.varHandle(MemoryLayout.PathElement.groupElement("unwrap_object"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5VL_wrap_class_t.free_wrap_ctx.class, "apply", constants$15.const$4);
}


