// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$193 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$193() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$192.const$4
    );
    static final VarHandle const$1 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("set_eoa"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5FD_class_t.get_eof.class, "apply", constants$192.const$0);
    static final VarHandle const$3 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_eof"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5FD_class_t.get_handle.class, "apply", constants$18.const$0);
    static final VarHandle const$5 = constants$184.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_handle"));
}


