// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$372 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$372() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5FD_class_t.read_vector.class, "apply", constants$372.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$372.const$0
    );
    static final VarHandle const$3 = constants$361.const$2.varHandle(MemoryLayout.PathElement.groupElement("read_vector"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5FD_class_t.write_vector.class, "apply", constants$372.const$0);
    static final VarHandle const$5 = constants$361.const$2.varHandle(MemoryLayout.PathElement.groupElement("write_vector"));
}


