// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$162 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$162() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Epop",
        constants$40.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Eprint2",
        constants$44.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Ewalk2",
        constants$162.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Eget_auto2",
        constants$41.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Eset_auto2",
        constants$41.const$4
    );
}


