// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$344 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$344() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_alloc_time",
        constants$64.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_chunk",
        constants$20.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pset_chunk_opts",
        constants$64.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_dset_no_attrs_hint",
        constants$183.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pset_external",
        constants$61.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_fill_time",
        constants$64.const$2
    );
}


