// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fclose",
        constants$15.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "tmpfile",
        constants$110.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tmpnam",
        constants$110.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tmpnam_r",
        constants$110.const$3
    );
}


