// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$207 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$207() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5MM_allocate_t.class, "apply", constants$206.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$206.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5MM_free_t.class, "apply", constants$115.const$5);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$115.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Sclose",
        constants$19.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Scopy",
        constants$10.const$2
    );
}


