// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$232 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$232() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pregister2",
        constants$232.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Premove",
        constants$44.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset",
        constants$41.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Punregister",
        constants$44.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pall_filters_avail",
        constants$19.const$0
    );
}


