// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$217 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$217() {}
    static final VarHandle const$0 = constants$216.const$2.varHandle(MemoryLayout.PathElement.groupElement("decoder_present"));
    static final VarHandle const$1 = constants$216.const$2.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$2 = constants$216.const$2.varHandle(MemoryLayout.PathElement.groupElement("can_apply"));
    static final VarHandle const$3 = constants$216.const$2.varHandle(MemoryLayout.PathElement.groupElement("set_local"));
    static final VarHandle const$4 = constants$216.const$2.varHandle(MemoryLayout.PathElement.groupElement("filter"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Zregister",
        constants$15.const$4
    );
}


