// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$438 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$438() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("version"),
        MemoryLayout.paddingLayout(7),
        JAVA_LONG.withName("backing_fapl_id"),
        JAVA_INT.withName("page_size"),
        JAVA_INT.withName("store_target"),
        JAVA_LONG.withName("revision_num"),
        JAVA_BYTE.withName("force_write_open"),
        JAVA_BYTE.withName("creation_flags"),
        MemoryLayout.sequenceLayout(256, JAVA_BYTE).withName("comment"),
        MemoryLayout.paddingLayout(6)
    ).withName("H5FD_onion_fapl_info_t");
    static final VarHandle const$1 = constants$438.const$0.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final VarHandle const$2 = constants$438.const$0.varHandle(MemoryLayout.PathElement.groupElement("backing_fapl_id"));
    static final VarHandle const$3 = constants$438.const$0.varHandle(MemoryLayout.PathElement.groupElement("page_size"));
    static final VarHandle const$4 = constants$438.const$0.varHandle(MemoryLayout.PathElement.groupElement("store_target"));
    static final VarHandle const$5 = constants$438.const$0.varHandle(MemoryLayout.PathElement.groupElement("revision_num"));
}


