// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("__count"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("__wch"),
            MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
        ).withName("__value")
    ).withName("");
    static final VarHandle const$1 = constants$103.const$0.varHandle(MemoryLayout.PathElement.groupElement("__count"));
    static final UnionLayout const$2 = MemoryLayout.unionLayout(
        JAVA_INT.withName("__wch"),
        MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
    ).withName("");
    static final VarHandle const$3 = constants$103.const$2.varHandle(MemoryLayout.PathElement.groupElement("__wch"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("__pos"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("__count"),
            MemoryLayout.unionLayout(
                JAVA_INT.withName("__wch"),
                MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("__wchb")
            ).withName("__value")
        ).withName("__state")
    ).withName("_G_fpos_t");
    static final VarHandle const$5 = constants$103.const$4.varHandle(MemoryLayout.PathElement.groupElement("__pos"));
}


