// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$231 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$231() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("op_type"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                JAVA_LONG.withName("type_id")
            ).withName("flush"),
            MemoryLayout.structLayout(
                JAVA_LONG.withName("type_id")
            ).withName("refresh")
        ).withName("args")
    ).withName("H5VL_datatype_specific_args_t");
    static final VarHandle const$1 = constants$231.const$0.varHandle(MemoryLayout.PathElement.groupElement("op_type"));
    static final UnionLayout const$2 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            JAVA_LONG.withName("type_id")
        ).withName("flush"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("type_id")
        ).withName("refresh")
    ).withName("");
    static final VarHandle const$3 = constants$222.const$1.varHandle(MemoryLayout.PathElement.groupElement("type_id"));
    static final VarHandle const$4 = constants$222.const$1.varHandle(MemoryLayout.PathElement.groupElement("type_id"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("version"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("feature_flags"),
        JAVA_LONG.withName("token_size"),
        JAVA_LONG.withName("blob_id_size")
    ).withName("H5VL_file_cont_info_t");
}


