// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$406 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$406() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5VLdataset_optional",
        constants$261.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5VLdataset_close",
        constants$404.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_commit",
        constants$402.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_open",
        constants$403.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_get",
        constants$261.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_specific",
        constants$261.const$3
    );
}


