// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$188 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$188() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5FD_class_t.read.class, "apply", constants$187.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$187.const$5
    );
    static final VarHandle const$2 = constants$178.const$0.varHandle(MemoryLayout.PathElement.groupElement("read"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(H5FD_class_t.write.class, "apply", constants$187.const$5);
    static final VarHandle const$4 = constants$178.const$0.varHandle(MemoryLayout.PathElement.groupElement("write"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_BOOLEAN
    );
}


