// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final VarHandle const$0 = constants$126.const$3.varHandle(MemoryLayout.PathElement.groupElement("min_num"));
    static final VarHandle const$1 = constants$126.const$3.varHandle(MemoryLayout.PathElement.groupElement("line"));
    static final VarHandle const$2 = constants$126.const$3.varHandle(MemoryLayout.PathElement.groupElement("func_name"));
    static final VarHandle const$3 = constants$126.const$3.varHandle(MemoryLayout.PathElement.groupElement("file_name"));
    static final VarHandle const$4 = constants$126.const$3.varHandle(MemoryLayout.PathElement.groupElement("desc"));
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5E_ERR_CLS_g", JAVA_LONG);
}


