// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$349 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$349() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_data_transform",
        constants$19.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_edc_check",
        constants$19.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_hyper_vector_size",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_preserve",
        constants$19.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_type_conv_cb",
        constants$36.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_vlen_mem_manager",
        constants$93.const$0
    );
}


