// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final VarHandle const$0 = constants$59.const$2.varHandle(MemoryLayout.PathElement.groupElement("query_func"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5L_iterate1_t.class, "apply", constants$61.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Lget_info1",
        constants$44.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Lget_info_by_idx1",
        constants$64.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Literate1",
        constants$65.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Literate_by_name1",
        constants$65.const$2
    );
}


