// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$179 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$179() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Fincrement_filesize",
        constants$41.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Fget_file_image",
        constants$20.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_config",
        constants$18.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Fset_mdc_config",
        constants$18.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_hit_rate",
        constants$18.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Fget_mdc_size",
        constants$103.const$5
    );
}


