// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$127 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$127() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "clearerr_unlocked",
        constants$116.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "feof_unlocked",
        constants$15.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ferror_unlocked",
        constants$15.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "perror",
        constants$116.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fileno",
        constants$15.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fileno_unlocked",
        constants$15.const$2
    );
}


