// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*H5_atclose_func_t)(void* ctx);
 * }
 */
public interface H5_atclose_func_t {

    void apply(java.lang.foreign.MemorySegment ctx);
    static MemorySegment allocate(H5_atclose_func_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$13.const$0, fi, constants$12.const$5, scope);
    }
    static H5_atclose_func_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _ctx) -> {
            try {
                constants$13.const$1.invokeExact(symbol, _ctx);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


