// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*H5I_future_realize_func_t)(void* future_object,long* actual_object_id);
 * }
 */
public interface H5I_future_realize_func_t {

    int apply(java.lang.foreign.MemorySegment future_object, java.lang.foreign.MemorySegment actual_object_id);
    static MemorySegment allocate(H5I_future_realize_func_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$385.const$1, fi, constants$13.const$4, scope);
    }
    static H5I_future_realize_func_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _future_object, java.lang.foreign.MemorySegment _actual_object_id) -> {
            try {
                return (int)constants$17.const$1.invokeExact(symbol, _future_object, _actual_object_id);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


