// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*H5P_prp_get_func_t)(long,char*,unsigned long,void*);
 * }
 */
public interface H5P_prp_get_func_t {

    int apply(long prop_id, java.lang.foreign.MemorySegment name, long size, java.lang.foreign.MemorySegment value);
    static MemorySegment allocate(H5P_prp_get_func_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$312.const$4, fi, constants$206.const$1, scope);
    }
    static H5P_prp_get_func_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _prop_id, java.lang.foreign.MemorySegment _name, long _size, java.lang.foreign.MemorySegment _value) -> {
            try {
                return (int)constants$312.const$1.invokeExact(symbol, _prop_id, _name, _size, _value);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


