// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_loc_by_token {
 *     H5O_token_t* token;
 * };
 * }
 */
public class H5VL_loc_by_token {

    public static MemoryLayout $LAYOUT() {
        return constants$218.const$0;
    }
    public static VarHandle token$VH() {
        return constants$218.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * H5O_token_t* token;
     * }
     */
    public static MemorySegment token$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$218.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * H5O_token_t* token;
     * }
     */
    public static void token$set(MemorySegment seg, MemorySegment x) {
        constants$218.const$1.set(seg, x);
    }
    public static MemorySegment token$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$218.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void token$set(MemorySegment seg, long index, MemorySegment x) {
        constants$218.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


