// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_attr_specific_args_t {
 *     H5VL_attr_specific_t op_type;
 *     union  args;
 * };
 * }
 */
public class H5VL_attr_specific_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$224.const$1;
    }
    public static VarHandle op_type$VH() {
        return constants$224.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * H5VL_attr_specific_t op_type;
     * }
     */
    public static int op_type$get(MemorySegment seg) {
        return (int)constants$224.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * H5VL_attr_specific_t op_type;
     * }
     */
    public static void op_type$set(MemorySegment seg, int x) {
        constants$224.const$2.set(seg, x);
    }
    public static int op_type$get(MemorySegment seg, long index) {
        return (int)constants$224.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void op_type$set(MemorySegment seg, long index, int x) {
        constants$224.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * union {
     *     struct  del;
     *     H5VL_attr_delete_by_idx_args_t delete_by_idx;
     *     struct  exists;
     *     H5VL_attr_iterate_args_t iterate;
     *     struct  rename;
     * };
     * }
     */
    public static final class args {

        // Suppresses default constructor, ensuring non-instantiability.
        private args() {}
        public static MemoryLayout $LAYOUT() {
            return constants$224.const$3;
        }
        /**
         * {@snippet :
         * struct {
         *     char* name;
         * };
         * }
         */
        public static final class del {

            // Suppresses default constructor, ensuring non-instantiability.
            private del() {}
            public static MemoryLayout $LAYOUT() {
                return constants$224.const$4;
            }
            public static VarHandle name$VH() {
                return constants$224.const$5;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* name;
             * }
             */
            public static MemorySegment name$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$224.const$5.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* name;
             * }
             */
            public static void name$set(MemorySegment seg, MemorySegment x) {
                constants$224.const$5.set(seg, x);
            }
            public static MemorySegment name$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$224.const$5.get(seg.asSlice(index*sizeof()));
            }
            public static void name$set(MemorySegment seg, long index, MemorySegment x) {
                constants$224.const$5.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment del$slice(MemorySegment seg) {
            return seg.asSlice(0, 8);
        }
        public static MemorySegment delete_by_idx$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        /**
         * {@snippet :
         * struct {
         *     char* name;
         *     hbool_t* exists;
         * };
         * }
         */
        public static final class exists {

            // Suppresses default constructor, ensuring non-instantiability.
            private exists() {}
            public static MemoryLayout $LAYOUT() {
                return constants$225.const$0;
            }
            public static VarHandle name$VH() {
                return constants$225.const$1;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* name;
             * }
             */
            public static MemorySegment name$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$225.const$1.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* name;
             * }
             */
            public static void name$set(MemorySegment seg, MemorySegment x) {
                constants$225.const$1.set(seg, x);
            }
            public static MemorySegment name$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$225.const$1.get(seg.asSlice(index*sizeof()));
            }
            public static void name$set(MemorySegment seg, long index, MemorySegment x) {
                constants$225.const$1.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle exists$VH() {
                return constants$225.const$2;
            }
            /**
             * Getter for field:
             * {@snippet :
             * hbool_t* exists;
             * }
             */
            public static MemorySegment exists$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$225.const$2.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * hbool_t* exists;
             * }
             */
            public static void exists$set(MemorySegment seg, MemorySegment x) {
                constants$225.const$2.set(seg, x);
            }
            public static MemorySegment exists$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$225.const$2.get(seg.asSlice(index*sizeof()));
            }
            public static void exists$set(MemorySegment seg, long index, MemorySegment x) {
                constants$225.const$2.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment exists$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        public static MemorySegment iterate$slice(MemorySegment seg) {
            return seg.asSlice(0, 32);
        }
        /**
         * {@snippet :
         * struct {
         *     char* old_name;
         *     char* new_name;
         * };
         * }
         */
        public static final class rename {

            // Suppresses default constructor, ensuring non-instantiability.
            private rename() {}
            public static MemoryLayout $LAYOUT() {
                return constants$225.const$3;
            }
            public static VarHandle old_name$VH() {
                return constants$225.const$4;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* old_name;
             * }
             */
            public static MemorySegment old_name$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$225.const$4.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* old_name;
             * }
             */
            public static void old_name$set(MemorySegment seg, MemorySegment x) {
                constants$225.const$4.set(seg, x);
            }
            public static MemorySegment old_name$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$225.const$4.get(seg.asSlice(index*sizeof()));
            }
            public static void old_name$set(MemorySegment seg, long index, MemorySegment x) {
                constants$225.const$4.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle new_name$VH() {
                return constants$225.const$5;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* new_name;
             * }
             */
            public static MemorySegment new_name$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$225.const$5.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* new_name;
             * }
             */
            public static void new_name$set(MemorySegment seg, MemorySegment x) {
                constants$225.const$5.set(seg, x);
            }
            public static MemorySegment new_name$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$225.const$5.get(seg.asSlice(index*sizeof()));
            }
            public static void new_name$set(MemorySegment seg, long index, MemorySegment x) {
                constants$225.const$5.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment rename$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment args$slice(MemorySegment seg) {
        return seg.asSlice(8, 32);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


