// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_token_class_t {
 *     herr_t (*cmp)(void*,const H5O_token_t*,const H5O_token_t*,int*);
 *     herr_t (*to_str)(void*,H5I_type_t,const H5O_token_t*,char**);
 *     herr_t (*from_str)(void*,H5I_type_t,char*,H5O_token_t*);
 * };
 * }
 */
public class H5VL_token_class_t {

    public static MemoryLayout $LAYOUT() {
        return constants$286.const$4;
    }
    /**
     * {@snippet :
 * herr_t (*cmp)(void*,const H5O_token_t*,const H5O_token_t*,int*);
     * }
     */
    public interface cmp {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2, java.lang.foreign.MemorySegment _x3);
        static MemorySegment allocate(cmp fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$286.const$5, fi, constants$14.const$5, scope);
        }
        static cmp ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2, java.lang.foreign.MemorySegment __x3) -> {
                try {
                    return (int)constants$287.const$0.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle cmp$VH() {
        return constants$287.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * herr_t (*cmp)(void*,const H5O_token_t*,const H5O_token_t*,int*);
     * }
     */
    public static MemorySegment cmp$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$287.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * herr_t (*cmp)(void*,const H5O_token_t*,const H5O_token_t*,int*);
     * }
     */
    public static void cmp$set(MemorySegment seg, MemorySegment x) {
        constants$287.const$1.set(seg, x);
    }
    public static MemorySegment cmp$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$287.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void cmp$set(MemorySegment seg, long index, MemorySegment x) {
        constants$287.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static cmp cmp(MemorySegment segment, Arena scope) {
        return cmp.ofAddress(cmp$get(segment), scope);
    }
    /**
     * {@snippet :
 * herr_t (*to_str)(void*,H5I_type_t,const H5O_token_t*,char**);
     * }
     */
    public interface to_str {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, java.lang.foreign.MemorySegment _x2, java.lang.foreign.MemorySegment _x3);
        static MemorySegment allocate(to_str fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$287.const$3, fi, constants$287.const$2, scope);
        }
        static to_str ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, java.lang.foreign.MemorySegment __x2, java.lang.foreign.MemorySegment __x3) -> {
                try {
                    return (int)constants$287.const$4.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle to_str$VH() {
        return constants$287.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * herr_t (*to_str)(void*,H5I_type_t,const H5O_token_t*,char**);
     * }
     */
    public static MemorySegment to_str$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$287.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * herr_t (*to_str)(void*,H5I_type_t,const H5O_token_t*,char**);
     * }
     */
    public static void to_str$set(MemorySegment seg, MemorySegment x) {
        constants$287.const$5.set(seg, x);
    }
    public static MemorySegment to_str$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$287.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void to_str$set(MemorySegment seg, long index, MemorySegment x) {
        constants$287.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static to_str to_str(MemorySegment segment, Arena scope) {
        return to_str.ofAddress(to_str$get(segment), scope);
    }
    /**
     * {@snippet :
 * herr_t (*from_str)(void*,H5I_type_t,char*,H5O_token_t*);
     * }
     */
    public interface from_str {

        int apply(java.lang.foreign.MemorySegment _x0, int _x1, java.lang.foreign.MemorySegment _x2, java.lang.foreign.MemorySegment _x3);
        static MemorySegment allocate(from_str fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$288.const$0, fi, constants$287.const$2, scope);
        }
        static from_str ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, int __x1, java.lang.foreign.MemorySegment __x2, java.lang.foreign.MemorySegment __x3) -> {
                try {
                    return (int)constants$287.const$4.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle from_str$VH() {
        return constants$288.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * herr_t (*from_str)(void*,H5I_type_t,char*,H5O_token_t*);
     * }
     */
    public static MemorySegment from_str$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$288.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * herr_t (*from_str)(void*,H5I_type_t,char*,H5O_token_t*);
     * }
     */
    public static void from_str$set(MemorySegment seg, MemorySegment x) {
        constants$288.const$1.set(seg, x);
    }
    public static MemorySegment from_str$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$288.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void from_str$set(MemorySegment seg, long index, MemorySegment x) {
        constants$288.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static from_str from_str(MemorySegment segment, Arena scope) {
        return from_str.ofAddress(from_str$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


