// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_file_get_obj_ids_args_t {
 *     unsigned int types;
 *     size_t max_objs;
 *     hid_t* oid_list;
 *     size_t* count;
 * };
 * }
 */
public class H5VL_file_get_obj_ids_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$233.const$3;
    }
    public static VarHandle types$VH() {
        return constants$233.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int types;
     * }
     */
    public static int types$get(MemorySegment seg) {
        return (int)constants$233.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int types;
     * }
     */
    public static void types$set(MemorySegment seg, int x) {
        constants$233.const$4.set(seg, x);
    }
    public static int types$get(MemorySegment seg, long index) {
        return (int)constants$233.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void types$set(MemorySegment seg, long index, int x) {
        constants$233.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_objs$VH() {
        return constants$233.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t max_objs;
     * }
     */
    public static long max_objs$get(MemorySegment seg) {
        return (long)constants$233.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t max_objs;
     * }
     */
    public static void max_objs$set(MemorySegment seg, long x) {
        constants$233.const$5.set(seg, x);
    }
    public static long max_objs$get(MemorySegment seg, long index) {
        return (long)constants$233.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void max_objs$set(MemorySegment seg, long index, long x) {
        constants$233.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle oid_list$VH() {
        return constants$234.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * hid_t* oid_list;
     * }
     */
    public static MemorySegment oid_list$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$234.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * hid_t* oid_list;
     * }
     */
    public static void oid_list$set(MemorySegment seg, MemorySegment x) {
        constants$234.const$0.set(seg, x);
    }
    public static MemorySegment oid_list$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$234.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void oid_list$set(MemorySegment seg, long index, MemorySegment x) {
        constants$234.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle count$VH() {
        return constants$234.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t* count;
     * }
     */
    public static MemorySegment count$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$234.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t* count;
     * }
     */
    public static void count$set(MemorySegment seg, MemorySegment x) {
        constants$234.const$1.set(seg, x);
    }
    public static MemorySegment count$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$234.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, MemorySegment x) {
        constants$234.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


