// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * union H5VL_native_object_optional_args_t {
 *     H5VL_native_object_get_comment_t get_comment;
 *     struct  set_comment;
 *     struct  are_mdc_flushes_disabled;
 *     H5VL_native_object_get_native_info_t get_native_info;
 * };
 * }
 */
public class H5VL_native_object_optional_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$434.const$1;
    }
    public static MemorySegment get_comment$slice(MemorySegment seg) {
        return seg.asSlice(0, 24);
    }
    /**
     * {@snippet :
     * struct {
     *     char* comment;
     * };
     * }
     */
    public static final class set_comment {

        // Suppresses default constructor, ensuring non-instantiability.
        private set_comment() {}
        public static MemoryLayout $LAYOUT() {
            return constants$434.const$2;
        }
        public static VarHandle comment$VH() {
            return constants$434.const$3;
        }
        /**
         * Getter for field:
         * {@snippet :
         * char* comment;
         * }
         */
        public static MemorySegment comment$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$434.const$3.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * char* comment;
         * }
         */
        public static void comment$set(MemorySegment seg, MemorySegment x) {
            constants$434.const$3.set(seg, x);
        }
        public static MemorySegment comment$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$434.const$3.get(seg.asSlice(index*sizeof()));
        }
        public static void comment$set(MemorySegment seg, long index, MemorySegment x) {
            constants$434.const$3.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment set_comment$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    /**
     * {@snippet :
     * struct {
     *     hbool_t* flag;
     * };
     * }
     */
    public static final class are_mdc_flushes_disabled {

        // Suppresses default constructor, ensuring non-instantiability.
        private are_mdc_flushes_disabled() {}
        public static MemoryLayout $LAYOUT() {
            return constants$434.const$4;
        }
        public static VarHandle flag$VH() {
            return constants$434.const$5;
        }
        /**
         * Getter for field:
         * {@snippet :
         * hbool_t* flag;
         * }
         */
        public static MemorySegment flag$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$434.const$5.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * hbool_t* flag;
         * }
         */
        public static void flag$set(MemorySegment seg, MemorySegment x) {
            constants$434.const$5.set(seg, x);
        }
        public static MemorySegment flag$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$434.const$5.get(seg.asSlice(index*sizeof()));
        }
        public static void flag$set(MemorySegment seg, long index, MemorySegment x) {
            constants$434.const$5.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment are_mdc_flushes_disabled$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment get_native_info$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


