// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_attr_get_name_args_t {
 *     H5VL_loc_params_t loc_params;
 *     size_t buf_size;
 *     char* buf;
 *     size_t* attr_name_len;
 * };
 * }
 */
public class H5VL_attr_get_name_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$219.const$3;
    }
    public static MemorySegment loc_params$slice(MemorySegment seg) {
        return seg.asSlice(0, 40);
    }
    public static VarHandle buf_size$VH() {
        return constants$219.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t buf_size;
     * }
     */
    public static long buf_size$get(MemorySegment seg) {
        return (long)constants$219.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t buf_size;
     * }
     */
    public static void buf_size$set(MemorySegment seg, long x) {
        constants$219.const$4.set(seg, x);
    }
    public static long buf_size$get(MemorySegment seg, long index) {
        return (long)constants$219.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void buf_size$set(MemorySegment seg, long index, long x) {
        constants$219.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle buf$VH() {
        return constants$219.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* buf;
     * }
     */
    public static MemorySegment buf$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$219.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* buf;
     * }
     */
    public static void buf$set(MemorySegment seg, MemorySegment x) {
        constants$219.const$5.set(seg, x);
    }
    public static MemorySegment buf$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$219.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void buf$set(MemorySegment seg, long index, MemorySegment x) {
        constants$219.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle attr_name_len$VH() {
        return constants$220.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t* attr_name_len;
     * }
     */
    public static MemorySegment attr_name_len$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$220.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t* attr_name_len;
     * }
     */
    public static void attr_name_len$set(MemorySegment seg, MemorySegment x) {
        constants$220.const$0.set(seg, x);
    }
    public static MemorySegment attr_name_len$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$220.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void attr_name_len$set(MemorySegment seg, long index, MemorySegment x) {
        constants$220.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


