// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_loc_params_t {
 *     H5I_type_t obj_type;
 *     H5VL_loc_type_t type;
 *     union  loc_data;
 * };
 * }
 */
public class H5VL_loc_params_t {

    public static MemoryLayout $LAYOUT() {
        return constants$218.const$2;
    }
    public static VarHandle obj_type$VH() {
        return constants$218.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * H5I_type_t obj_type;
     * }
     */
    public static int obj_type$get(MemorySegment seg) {
        return (int)constants$218.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * H5I_type_t obj_type;
     * }
     */
    public static void obj_type$set(MemorySegment seg, int x) {
        constants$218.const$3.set(seg, x);
    }
    public static int obj_type$get(MemorySegment seg, long index) {
        return (int)constants$218.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void obj_type$set(MemorySegment seg, long index, int x) {
        constants$218.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle type$VH() {
        return constants$218.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * H5VL_loc_type_t type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$218.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * H5VL_loc_type_t type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$218.const$4.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$218.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$218.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * union {
     *     H5VL_loc_by_token_t loc_by_token;
     *     H5VL_loc_by_name_t loc_by_name;
     *     H5VL_loc_by_idx_t loc_by_idx;
     * };
     * }
     */
    public static final class loc_data {

        // Suppresses default constructor, ensuring non-instantiability.
        private loc_data() {}
        public static MemoryLayout $LAYOUT() {
            return constants$218.const$5;
        }
        public static MemorySegment loc_by_token$slice(MemorySegment seg) {
            return seg.asSlice(0, 8);
        }
        public static MemorySegment loc_by_name$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        public static MemorySegment loc_by_idx$slice(MemorySegment seg) {
            return seg.asSlice(0, 32);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment loc_data$slice(MemorySegment seg) {
        return seg.asSlice(8, 32);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


