// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * union H5VL_native_group_optional_args_t {
 *     H5VL_native_group_iterate_old_t iterate_old;
 *     H5VL_native_group_get_objinfo_t get_objinfo;
 * };
 * }
 */
public class H5VL_native_group_optional_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$432.const$5;
    }
    public static MemorySegment iterate_old$slice(MemorySegment seg) {
        return seg.asSlice(0, 72);
    }
    public static MemorySegment get_objinfo$slice(MemorySegment seg) {
        return seg.asSlice(0, 56);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


