// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*H5Z_set_local_func_t)(long dcpl_id,long type_id,long space_id);
 * }
 */
public interface H5Z_set_local_func_t {

    int apply(long dcpl_id, long type_id, long space_id);
    static MemorySegment allocate(H5Z_set_local_func_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$216.const$2, fi, constants$215.const$5, scope);
    }
    static H5Z_set_local_func_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _dcpl_id, long _type_id, long _space_id) -> {
            try {
                return (int)constants$216.const$1.invokeExact(symbol, _dcpl_id, _type_id, _space_id);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


