// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$119 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$119() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fputc_unlocked",
        constants$22.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "putc_unlocked",
        constants$22.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "putchar_unlocked",
        constants$21.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getw",
        constants$15.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "putw",
        constants$22.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "fgets",
        constants$119.const$5
    );
}


