// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$290 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$290() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$13.const$2
    );
    static final VarHandle const$1 = constants$288.const$2.varHandle(MemoryLayout.PathElement.groupElement("terminate"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_class_t.optional.class, "apply", constants$262.const$3);
    static final VarHandle const$3 = constants$288.const$2.varHandle(MemoryLayout.PathElement.groupElement("optional"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VLregister_connector",
        constants$208.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLobject",
        constants$63.const$5
    );
}


