// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$277 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$277() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(H5VL_link_class_t.move.class, "apply", constants$276.const$2);
    static final VarHandle const$1 = constants$275.const$3.varHandle(MemoryLayout.PathElement.groupElement("move"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_link_class_t.get.class, "apply", constants$263.const$1);
    static final VarHandle const$3 = constants$275.const$3.varHandle(MemoryLayout.PathElement.groupElement("get"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(H5VL_link_class_t.specific.class, "apply", constants$263.const$1);
    static final VarHandle const$5 = constants$275.const$3.varHandle(MemoryLayout.PathElement.groupElement("specific"));
}


