// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$433 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$433() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("buf_size"),
        RuntimeHelper.POINTER.withName("buf"),
        RuntimeHelper.POINTER.withName("comment_len")
    ).withName("H5VL_native_object_get_comment_t");
    static final VarHandle const$1 = constants$433.const$0.varHandle(MemoryLayout.PathElement.groupElement("buf_size"));
    static final VarHandle const$2 = constants$433.const$0.varHandle(MemoryLayout.PathElement.groupElement("buf"));
    static final VarHandle const$3 = constants$433.const$0.varHandle(MemoryLayout.PathElement.groupElement("comment_len"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("fields"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("ninfo")
    ).withName("H5VL_native_object_get_native_info_t");
    static final VarHandle const$5 = constants$433.const$4.varHandle(MemoryLayout.PathElement.groupElement("fields"));
}


