// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$283 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$283() {}
    static final VarHandle const$0 = constants$282.const$4.varHandle(MemoryLayout.PathElement.groupElement("wait"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5VL_request_class_t.notify.class, "apply", constants$15.const$0);
    static final VarHandle const$2 = constants$282.const$4.varHandle(MemoryLayout.PathElement.groupElement("notify"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(H5VL_request_class_t.cancel.class, "apply", constants$13.const$4);
    static final VarHandle const$4 = constants$282.const$4.varHandle(MemoryLayout.PathElement.groupElement("cancel"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5VL_request_class_t.specific.class, "apply", constants$13.const$4);
}


