// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$441 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$441() {}
    static final VarHandle const$0 = constants$440.const$2.varHandle(MemoryLayout.PathElement.groupElement("wo_fapl_id"));
    static final VarHandle const$1 = constants$440.const$2.varHandle(MemoryLayout.PathElement.groupElement("ignore_wo_errs"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5FD_splitter_init",
        constants$159.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_fapl_splitter",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_fapl_splitter",
        constants$17.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5FD_stdio_init",
        constants$159.const$0
    );
}


