// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$412 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$412() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5VLintrospect_get_cap_flags",
        constants$17.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5VLintrospect_opt_query",
        constants$412.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5VLrequest_wait",
        constants$404.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VLrequest_notify",
        constants$115.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLrequest_cancel",
        constants$17.const$2
    );
}


