// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$260 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$260() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("create"),
        RuntimeHelper.POINTER.withName("open"),
        RuntimeHelper.POINTER.withName("read"),
        RuntimeHelper.POINTER.withName("write"),
        RuntimeHelper.POINTER.withName("get"),
        RuntimeHelper.POINTER.withName("specific"),
        RuntimeHelper.POINTER.withName("optional"),
        RuntimeHelper.POINTER.withName("close")
    ).withName("H5VL_attr_class_t");
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_attr_class_t.create.class, "apply", constants$260.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$260.const$1
    );
    static final VarHandle const$4 = constants$260.const$0.varHandle(MemoryLayout.PathElement.groupElement("create"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
}


