// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$442 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$442() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pset_fapl_stdio",
        constants$19.const$1
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_LONG.withName("under_vol_id"),
        RuntimeHelper.POINTER.withName("under_vol_info")
    ).withName("H5VL_pass_through_info_t");
    static final VarHandle const$2 = constants$442.const$1.varHandle(MemoryLayout.PathElement.groupElement("under_vol_id"));
    static final VarHandle const$3 = constants$442.const$1.varHandle(MemoryLayout.PathElement.groupElement("under_vol_info"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VL_pass_through_register",
        constants$159.const$0
    );
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/usr/local/hdf5/lib/plugin");
}


