// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$334 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$334() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_mdc_image_config",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_mdc_log_options",
        constants$93.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_meta_block_size",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_metadata_read_attempts",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_multi_type",
        constants$17.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_object_flush_cb",
        constants$36.const$1
    );
}


