// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$22.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(H5E_auto2_t.class, "apply", constants$17.const$5);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Eregister_class",
        constants$120.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Eunregister_class",
        constants$19.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Eclose_msg",
        constants$19.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Ecreate_msg",
        constants$63.const$0
    );
}


