// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$347 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$347() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Pget_virtual_prefix",
        constants$19.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pget_virtual_printf_gap",
        constants$17.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5Pget_virtual_view",
        constants$17.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pset_append_flush",
        constants$346.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_DOUBLE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pset_chunk_cache",
        constants$347.const$4
    );
}


