// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$289 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$289() {}
    static final VarHandle const$0 = constants$288.const$2.varHandle(MemoryLayout.PathElement.groupElement("conn_version"));
    static final VarHandle const$1 = constants$288.const$2.varHandle(MemoryLayout.PathElement.groupElement("cap_flags"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(H5VL_class_t.initialize.class, "apply", constants$19.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$19.const$1
    );
    static final VarHandle const$4 = constants$288.const$2.varHandle(MemoryLayout.PathElement.groupElement("initialize"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(H5VL_class_t.terminate.class, "apply", constants$13.const$2);
}


