// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$316 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$316() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_DATATYPE_CREATE_ID_g", JAVA_LONG);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_DATATYPE_ACCESS_ID_g", JAVA_LONG);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_MAP_CREATE_ID_g", JAVA_LONG);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_MAP_ACCESS_ID_g", JAVA_LONG);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_STRING_CREATE_ID_g", JAVA_LONG);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("H5P_CLS_ATTRIBUTE_CREATE_ID_g", JAVA_LONG);
}


