// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$407 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$407() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_optional",
        constants$261.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5VLdatatype_close",
        constants$404.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "H5VLfile_create",
        constants$270.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5VLfile_open",
        constants$271.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5VLfile_get",
        constants$261.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5VLfile_specific",
        constants$261.const$3
    );
}


