// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$346 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$346() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Pset_virtual",
        constants$346.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Pget_append_flush",
        constants$346.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "H5Pget_chunk_cache",
        constants$27.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "H5Pget_efile_prefix",
        constants$19.const$4
    );
}


