// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "H5Tget_array_dims1",
        constants$36.const$1
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_BOOLEAN.withName("corder_valid"),
        MemoryLayout.paddingLayout(3),
        JAVA_INT.withName("corder"),
        JAVA_INT.withName("cset"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("data_size")
    ).withName("");
    static final VarHandle const$2 = constants$72.const$1.varHandle(MemoryLayout.PathElement.groupElement("corder_valid"));
    static final VarHandle const$3 = constants$72.const$1.varHandle(MemoryLayout.PathElement.groupElement("corder"));
    static final VarHandle const$4 = constants$72.const$1.varHandle(MemoryLayout.PathElement.groupElement("cset"));
    static final VarHandle const$5 = constants$72.const$1.varHandle(MemoryLayout.PathElement.groupElement("data_size"));
}


