// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$197 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$197() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "H5Lunpack_elink_val",
        constants$197.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "H5Lcreate_external",
        constants$197.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_BOOLEAN.withName("corder_valid"),
        MemoryLayout.paddingLayout(3),
        JAVA_LONG.withName("corder"),
        JAVA_INT.withName("cset"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            JAVA_LONG.withName("address"),
            JAVA_LONG.withName("val_size")
        ).withName("u")
    ).withName("");
    static final VarHandle const$5 = constants$197.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


