// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct H5VL_group_get_info_args_t {
 *     H5VL_loc_params_t loc_params;
 *     H5G_info_t* ginfo;
 * };
 * }
 */
public class H5VL_group_get_info_args_t {

    public static MemoryLayout $LAYOUT() {
        return constants$240.const$0;
    }
    public static MemorySegment loc_params$slice(MemorySegment seg) {
        return seg.asSlice(0, 40);
    }
    public static VarHandle ginfo$VH() {
        return constants$240.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * H5G_info_t* ginfo;
     * }
     */
    public static MemorySegment ginfo$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$240.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * H5G_info_t* ginfo;
     * }
     */
    public static void ginfo$set(MemorySegment seg, MemorySegment x) {
        constants$240.const$1.set(seg, x);
    }
    public static MemorySegment ginfo$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$240.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void ginfo$set(MemorySegment seg, long index, MemorySegment x) {
        constants$240.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


