// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * enum H5Z_cb_return_t (*H5Z_filter_func_t)(int filter,void* buf,unsigned long buf_size,void* op_data);
 * }
 */
public interface H5Z_filter_func_t {

    int apply(int filter, java.lang.foreign.MemorySegment buf, long buf_size, java.lang.foreign.MemorySegment op_data);
    static MemorySegment allocate(H5Z_filter_func_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$310.const$3, fi, constants$310.const$2, scope);
    }
    static H5Z_filter_func_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _filter, java.lang.foreign.MemorySegment _buf, long _buf_size, java.lang.foreign.MemorySegment _op_data) -> {
            try {
                return (int)constants$310.const$4.invokeExact(symbol, _filter, _buf, _buf_size, _op_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


